---
apt:
  all_update_flag: True
  all_upgrade_flag: True
  packages:
    - name: git
    - name: vim
    - name: wget
    - name: ghostscript
    - name: imagemagick
    - name: libcap2-bin
    - name: libnss3-tools
    - name: libimage-exiftool-perl
    - name: libavcodec-dev
    - name: libavformat-dev
    - name: libswscale-dev
    - name: ffmpeg

