---
- name: clone sage2 code
  git:
    repo: 'https://bitbucket.org/sage2/sage2.git'
    dest: /home/pi/sage2
    version: master

- name: chown
  file:
    path: /home/pi/sage2
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    recurse: yes
    mode: 0755

- name: sage2 go linux
  shell: ./GO-linux
  args:
    chdir: /home/pi/sage2/keys


