---
- name: clone sage2 code
  git:
    repo: 'https://bitbucket.org/sage2/sage2.git'
    dest: /home/pi/sage2
    version: master

- name: sage2 go linux
  shell: ./GO-linux
  args:
    chdir: /home/pi/sage2/keys

- name: copy config file
  copy:
    src: "{{ role_path }}/files/raspberrypi-cfg.json"
    dest: /home/pi/sage2/config/raspberrypi-cfg.json

- name: chown
  file:
    path: /home/pi/sage2
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    recurse: yes
    mode: 0755

