---

- name: set locale to '{{ sys.locale }}'
  locale_gen:
    name: '{{ sys.locale }}'
    state: present

- name: set timezone to '{{ sys.timezone }}'
  timezone:
    name: '{{ sys.timezone }}'
  
- name: start & stop services
  service:
    name: '{{ item.name }}'
    enabled: '{{ item.enabled | default("yes") }}'
    state: '{{ item.state | default("started") }}'
  with_items: '{{ sys.services }}'

- name: copy config file
  copy:
    src: "{{ role_path }}/files/config.txt"
    dest: /boot/config.txt
  become: True
